// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/myserver.proto

package myserver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Myserver service

func NewMyserverEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Myserver service

type MyserverService interface {
	SayHello(ctx context.Context, in *SayRequest, opts ...client.CallOption) (*SayResponse, error)
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Myserver_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Myserver_PingPongService, error)
}

type myserverService struct {
	c    client.Client
	name string
}

func NewMyserverService(name string, c client.Client) MyserverService {
	return &myserverService{
		c:    c,
		name: name,
	}
}

func (c *myserverService) SayHello(ctx context.Context, in *SayRequest, opts ...client.CallOption) (*SayResponse, error) {
	req := c.c.NewRequest(c.name, "Myserver.SayHello", in)
	out := new(SayResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myserverService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Myserver.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myserverService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Myserver_StreamService, error) {
	req := c.c.NewRequest(c.name, "Myserver.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &myserverServiceStream{stream}, nil
}

type Myserver_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type myserverServiceStream struct {
	stream client.Stream
}

func (x *myserverServiceStream) Close() error {
	return x.stream.Close()
}

func (x *myserverServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *myserverServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *myserverServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *myserverServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *myserverService) PingPong(ctx context.Context, opts ...client.CallOption) (Myserver_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Myserver.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &myserverServicePingPong{stream}, nil
}

type Myserver_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type myserverServicePingPong struct {
	stream client.Stream
}

func (x *myserverServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *myserverServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *myserverServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *myserverServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *myserverServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *myserverServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Myserver service

type MyserverHandler interface {
	SayHello(context.Context, *SayRequest, *SayResponse) error
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Myserver_StreamStream) error
	PingPong(context.Context, Myserver_PingPongStream) error
}

func RegisterMyserverHandler(s server.Server, hdlr MyserverHandler, opts ...server.HandlerOption) error {
	type myserver interface {
		SayHello(ctx context.Context, in *SayRequest, out *SayResponse) error
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Myserver struct {
		myserver
	}
	h := &myserverHandler{hdlr}
	return s.Handle(s.NewHandler(&Myserver{h}, opts...))
}

type myserverHandler struct {
	MyserverHandler
}

func (h *myserverHandler) SayHello(ctx context.Context, in *SayRequest, out *SayResponse) error {
	return h.MyserverHandler.SayHello(ctx, in, out)
}

func (h *myserverHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MyserverHandler.Call(ctx, in, out)
}

func (h *myserverHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MyserverHandler.Stream(ctx, m, &myserverStreamStream{stream})
}

type Myserver_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type myserverStreamStream struct {
	stream server.Stream
}

func (x *myserverStreamStream) Close() error {
	return x.stream.Close()
}

func (x *myserverStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *myserverStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *myserverStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *myserverStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *myserverHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MyserverHandler.PingPong(ctx, &myserverPingPongStream{stream})
}

type Myserver_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type myserverPingPongStream struct {
	stream server.Stream
}

func (x *myserverPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *myserverPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *myserverPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *myserverPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *myserverPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *myserverPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
